name: "X9Containers"
description: "Scans live intermediate containers for vulnerabilities during customized X9 Dockerfiles image building"
author: "OLX BR"
inputs:
  image:
    description: "target Docker Image"
    required: true
  x9container:
    description: "target X9Containers Dockerfile"
    required: true
runs:
  using: "composite"
  steps:
    - id: scan
      run: |
        curl https://raw.githubusercontent.com/olxbr/X9Containers/main/${X9CONTAINER}.X9.Dockerfile --output X9.Dockerfile

        echo "X9 will find something to blame now..."

        docker build -f X9.Dockerfile -t suspectimage --build-arg IMAGE=${IMAGE} .
        rm -rf X9.Dockerfile

        docker create --name suspectcontainer suspectimage
        docker cp suspectcontainer:/scans ./scans

        echo "******************************************************************************************************************************************"
        for i in scans/* ; do \
            cat $i ; \
            echo "*********************************************** END OF $i ***********************************************" ; \
        done

        if [[ $X9CONTAINER == *".critical"* ]]; then
          echo -n "Trivy	"
          grep "Total: 0 (CRITICAL: 0)" scans/image-vulnerabilities-trivy.txt;

          echo -n "ClamAV	"
          grep "Infected files: 0" scans/recursive-root-dir-clamscan.txt;
        fi        

        rm -rf scans
      env:
        IMAGE: ${{ inputs.image }}
        X9CONTAINER: ${{ inputs.x9container }}
      shell: bash
branding:
  icon: "check-circle"
  color: "blue"
