name: "X9Containers"
description: "Scans live intermediate containers for vulnerabilities during customized X9 Dockerfiles image building"
author: "OLX BR"
inputs:
  image:
    description: "target Docker Image"
    required: true
  distro:
    description: "target distro of Docker Image"
    required: true
  trivy_severity:
    description: "Trivy threat detection level"
    required: false
    default: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL"
  ignore_threats:
    description: "if true, don't interrupt workflow if has findings"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - id: scan
      run: |
        curl https://raw.githubusercontent.com/olxbr/X9Containers/main/${DISTRO}.X9.Dockerfile --output X9.Dockerfile
        echo "X9 will find something to blame now..."

        docker build -f X9.Dockerfile -t suspectimage --build-arg IMAGE=${IMAGE} --build-arg TRIVY_SEVERITY=${TRIVY_SEVERITY} --quiet .
        rm -rf X9.Dockerfile
        docker create --name suspectcontainer suspectimage
        docker cp suspectcontainer:/scans ./scans
        echo "******************************************************************************************************************************************"
        for i in scans/* ; do \
            cat $i ; \
            echo "*********************************************** END OF $i ***********************************************" ; \
        done

        if [[ $IGNORE_THREATS == "true" ]]; then
          echo "IGNORE_THREATS is true, skipping workflow interruption"
          rm -rf scans
          exit 0
        fi

        clam_scan_file="scans/recursive-root-dir-clamscan.txt"
        if [[ -f "$clam_scan_file" ]]; then
          echo -n "ClamAV	"
          grep "Infected files: 0" $clam_scan_file;
        fi

        trivy_scan_file="scans/image-vulnerabilities-trivy.txt"
        if [[ -f "$trivy_scan_file" ]]; then
          echo -n "Trivy	"
          if [[ $TRIVY_SEVERITY == "CRITICAL" ]]
          then
            grep "Total: 0 (CRITICAL: 0)" $trivy_scan_file;
          elif [[ $TRIVY_SEVERITY == "HIGH,CRITICAL" ]]
          then
            grep "Total: 0 (HIGH: 0, CRITICAL: 0)" $trivy_scan_file;
          elif [[ $TRIVY_SEVERITY == "MEDIUM,HIGH,CRITICAL" ]]
          then
            grep "Total: 0 (MEDIUM: 0, HIGH: 0, CRITICAL: 0)" $trivy_scan_file;
          elif [[ $TRIVY_SEVERITY == "LOW,MEDIUM,HIGH,CRITICAL" ]]
          then
            grep "Total: 0 (LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)" $trivy_scan_file;
          elif [[ $TRIVY_SEVERITY == "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL" ]]
          then
            grep "Total: 0 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)" $trivy_scan_file;
          else
            echo "Custom Trivy severity, ignoring interruption"
          fi
        fi

        rm -rf scans
      env:
        IMAGE: ${{ inputs.image }}
        DISTRO: ${{ inputs.distro }}
        TRIVY_SEVERITY: ${{ inputs.trivy_severity }}
        IGNORE_THREATS: ${{ inputs.ignore_threats }}
      shell: bash
branding:
  icon: "check-circle"
  color: "blue"
