name: "X9Containers"
description: "Scans live intermediate containers for vulnerabilities during customized X9 Dockerfiles image building"
author: "OLX BR"
inputs:
  image:
    description: "target Docker Image"
    required: true
  trivyEnabled:
    description: "Enable trivy scan"
    required: true
    default: "true"
  clamavEnabled:
    description: "Enable ClamAV scan"
    required: true
    default: "true"
  severity:
    description: "Trivy minimum threat threshold"
    required: false
    default: "UNKNOWN"
  ignoreThreats:
    description: "if true, don't interrupt workflow if has findings"
    required: false
    default: "false"

runs:
  using: "node12"
  main: 'dist/index.js'

branding:
  icon: "check-circle"
  color: "blue"
